@ApiRestful_HostAddress = http://localhost:5008

GET {{ApiRestful_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{ApiRestful_HostAddress}}/api/categorys/list

###

GET {{ApiRestful_HostAddress}}/api/categorys/0

###

POST {{ApiRestful_HostAddress}}/api/categorys/save
Content-Type: application/json

{
  //CategoryDTO
}

###

DELETE {{ApiRestful_HostAddress}}/api/wishlistitem/delete/0

###
